import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../components/header";


export const metadata: Metadata = {
  title: "Rest Book",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
   children: React.ReactNode
  }>) {
  return (
    <html lang="pt-BR">
      <body className="antialiased bg-gray-100">
        <Header />
        {children}
      </body>
    </html>
  );
}
